//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalCourseChallenge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int Id { get; set; }
        public System.DateTime MatchDate { get; set; }
        public string Venue { get; set; }
        public short Completed { get; set; }
        public decimal CourtFee { get; set; }
        public string WhoPaid { get; set; }
    }
}
